### ISSUE TITLE
"code not working "

### ISSUE THREAD

**Issue by adarshcode12** [Ashishkumar-hub/BERT-Extractive-Summerizer#1]
Traceback (most recent call last):
  File "d:\btech\3-YEAR\sem-6\NLP\project\extractive\BERT-Extractive-Summerizer-main\summarize.py", line 1, in <module>
    from summarizer import Summarizer
  File "d:\btech\3-YEAR\sem-6\NLP\project\extractive\BERT-Extractive-Summerizer-main\summarizer\__init__.py", line 1, in <module>
    from summarizer.model_processors import Summarizer, SingleModel, TransformerSummarizer
  File "d:\btech\3-YEAR\sem-6\NLP\project\extractive\BERT-Extractive-Summerizer-main\summarizer\model_processors.py", line 10, in <module>      
    class ModelProcessor(object):
  File "d:\btech\3-YEAR\sem-6\NLP\project\extractive\BERT-Extractive-Summerizer-main\summarizer\model_processors.py", line 19, in ModelProcessor
    sentence_handler: SentenceHandler = SentenceHandler(),
  File "d:\btech\3-YEAR\sem-6\NLP\project\extractive\BERT-Extractive-Summerizer-main\summarizer\sentence_handler.py", line 8, in __init__
    self.nlp.add_pipe(self.nlp.create_pipe('sentencizer'))
  File "C:\Users\Adarsh kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\language.py", line 773, in add_pipe
    raise ValueError(err)
ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <spacy.pipeline.sentencizer.Sentencizer object at 0x0000026F6EEB9480> (name: 'None').

- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

- If you're using a custom component: Add the decorator `@Language.component` (for function components) or `@Language.factory` (for class components / factories) to your custom 
component and assign it a name, e.g. `@Language.component('your_name')`. You can then run `nlp.add_pipe('your_name')` to add it to the pipeline.

**Comment by Ashishkumar-hub** [comment]
@adarshcode12  Its working fine on my laptop I am attaching an updated requirement.txt file kindly use that.
[requirement.txt](https://github.com/Ashishkumar-hub/BERT-Extractive-Summerizer/files/8504532/requirement.txt)
 
checkout the video on YT: https://youtu.be/ynYlqKgiZjM

**Comment by adarshcode12** [comment]
Processing c:\ci_310\cffi_1642682485096\work
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\ci_310\\cffi_1642682485096\\work'

don't have these files
please help as it is required for my project work

**Comment by Ashishkumar-hub** [comment]
@adarshcode12 its says the directory is not present kindly check the path I just ran this project again and its working file 

Just follow the below steps: 

> Download the zip file and extract it in your desktop 
> open the folder in any software ( I am using Pycharm )
> create a new conda environment and use the new requirement file (sent above I have attached the updated one for your convenience ) 
> After creating env and activating it just write pip install -r requirement.txt in terminal 
> Run summarize.py

Kindly reach out to me on mail (singh.ashish.kr96@gmail.com) for any further queries the code is working fine I am closing this issue.

**Comment by adarshcode12** [comment]
Hi Ashish,
Adarsh this side, i tried your steps mentioned above but get the error and
did not work.
If you can help me to solve this error which would ve a great help.
I have attaches the screenshort of the error message.
